# home/desktop.nix — KDE-flavoured home files.
#
# Every file here is hand-written rather than generated by a home-manager module
# on purpose:
#
#   - Zed's settings are a JSON blob and Zed ignores keys it does not know, so a
#     hand-written file cannot break on a Zed upgrade. A mis-named HM option
#     breaks the whole eval.
#   - Plasma's .conf files are read on top of its defaults at every session
#     start; writing four small files is cheaper and more portable than
#     depending on whatever HM's Plasma module does this month.
#
# The privacy settings in policies.json are the reason to use Zen at all here:
# telemetry, telemetry-adjacent "studies", Firefox accounts, Pocket, search
# suggestions and tracking all off, in a place the browser reads before the
# profile exists.
{ config, lib, pkgs, ...
}:
{
  config = lib.mkIf config.astra.desktop.enable {
    # ----------------------------------------------------------- ghostty ----
    xdg.configFile."ghostty/config".text = ''
      window-padding-x = 4
      window-padding-y = 4
      scrollback-limit = 10000
      clipboard-paste-protection = false
      window-decoration = false
      font-family = JetBrainsMono Nerd Font
      font-size = 12
      cursor-style = block
      cursor-style-blink = false
      copy-on-select = clipboard
      shell-integration = detect
      mouse-hide-while-typing = true
      background-opacity = 0.96
      background-blur-radius = 12
      confirm-close-surface = false
    '';

    # -------------------------------------------------------------- zen -----
    xdg.configFile."zen/policies.json".text = ''
      {
        "policies": {
          "DisableTelemetry": true,
          "DisablePocket": true,
          "DisableFirefoxStudies": true,
          "DisableFirefoxAccounts": true,
          "DisableFirefoxReports": true,
          "DontCheckDefaultBrowser": true,
          "DisableSetDesktopBackground": true,
          "DisableSystemAccount": true,
          "SearchSuggestEnabled": false,
          "CaptivePortal": false,
          "PromptForDownloadLocation": true,
          "ImportSanitize": true,
          "NetworkPrediction": false,
          "EnableTrackingProtection": true,
          "EnableFission": true,
          "HTTPSOnlyMode": { "Enabled": true, "Locked": true },
          "Cookies": { "Behavior": "reject-tracker-and-partition-foreign" },
          "DnsOverHTTPS": { "Enabled": true, "URL": "https://mozilla.cloudflare-dns.com/dns-query" },
          "PasswordManagerEnabled": true,
          "OfferToSaveLogins": true,
          "FirefoxSync": { "Enabled": false },
          "FirefoxHome": {
            "Search": true,
            "TopSites": false,
            "SponsoredTopSites": false,
            "Pocket": false,
            "SponsoredBottomPocket": false
          },
          "UserMessaging": {
            "WhatsNew": false,
            "ExtensionRecommendations": false,
            "FeatureRecommendations": false,
            "UrlbarInterventions": false,
            "SkipOnboarding": true
          },
          "SystemIntegration": { "AllowBrowserIntegration": false }
        }
      }
    '';

    # firefox from nixpkgs reads the same file, but from its own distribution
    # directory; HM's module puts it there.
    programs.firefox = {
      enable = true;
      policies.privacy.reduceTimerPrecision = false;
      policies."DisableFirefoxStudies".enabled = true;
    };

    # -------------------------------------------------------------- zed -----
    # Unknown keys are ignored by Zed, so this file is safe to grow.
    xdg.configFile."zed/settings.json".text = ''
      {
        "telemetry": false,
        "auto_update": "off",
        "vim_mode": false,
        "edit_prediction": false,
        "inlay_hints": { "for": "language_specific" },
        "buffer_font_size": 14,
        "ui_font_size": 15,
        "current_line_highlight": "all",
        "cursor_blink": "on",
        "scroll_beyond_last_line": false,
        "file_scan_exclusions": [
          "**/target",
          "**/node_modules",
          "**/.git",
          "**/.direnv",
          "**/result",
          "**/.venv"
        ],
        "file_triggers": {
          "**/.git/HEAD": [{ "formatter": "git-branch" }]
        }
      }
    '';

    # ------------------------------------------------------------ plasma ----
    # System-wide Plasma preferences. The session writes its own layout on top of
    # these, so they are defaults, not policy.
    xdg.configFile."kdeglobals".text = ''
      [General]
      Name=Breeze
      ColorScheme=BreezeDark
      Font=Noto Sans,10,-1,5,50,0,0,0,0,0
      Fixed=JetBrainsMono Nerd Font,10,50,0,0,0,0,0,0,0

      [Icons]
      Theme=breeze
    '';

    xdg.configFile."kwinrc".text = ''
      [Compositing]
      Backend=OpenGL

      [Magnetism]
      EdgeTolerance=10

      [MouseBindings]
      DoubleClick=MaximizeOrRestore
      Wheel=Desktops
    '';

    # The screen locks after ten idle minutes. Hyprlock used to do this on
    # Super+L; Plasma's own is better because it suspends with the screen.
    xdg.configFile."kscreenlockerrc".text = ''
      [Daemon]
      Autolock=true
      LockTimeout=10
    '';

    # Nautilus/Files is not what anyone actually uses here, but Plasma's file
    # dialog still is, and it should not show the home directory as a huge wall
    # of dotfiles. Trivial default that saves everyone a click.
    xdg.configFile."gtk-4.0/settings.ini".text = ''
      [Settings]
      gtk-icon-theme-name=breeze
      gtk-theme-name=Adwaita
      gtk-font-name=Noto Sans 10
    '';
  };
}