# base.nix — the root of the astra profile hierarchy.
#
# Every host imports exactly one entry point from profiles/, which transitively
# pulls in base -> core -> desktop. base.nix does two jobs and nothing else:
#
#   1. It *declares* the `astra.*` option surface. Options are declared exactly
#      once, here, at the root. That is what makes the rest of the hierarchy
#      predictable: core and desktop contribute to knobs that base has already
#      defined, so a host can override any of them without guessing which
#      module "owns" a setting.
#
#   2. It installs the small set of things that literally every machine needs,
#      including the account you log in as.
#
# Merge semantics — the whole point of the option surface:
#
#   astra.packages       listOf package    CONCATENATES down the hierarchy.
#   astra.dropPackages   listOf package    CONCATENATES, subtracted at the end.
#   everything else      last write wins. A profile uses the plain assignment;
#                        a host that must beat a profile uses `lib.mkForce`.
#
# The only supported way to remove something a lower profile added is
# `astra.dropPackages`, so removals are greppable in one place.
{ config, lib, pkgs, ... }:
let
  cfg = config.astra;

  # Read by `astra-info` and written to /etc/astra/profile so the running
  # machine can always tell you which stack it is running.
  profileFacts = ''
    # generated by astra (profiles/base.nix) — do not edit, do not commit
    host=${config.networking.hostName}
    profiles=${lib.concatStringsSep " " cfg.profiles}
    astraVersion=${cfg.version}
    nixpkgs=${config.system.nixos.version}
    nixpkgsRev=${if config.nixpkgs.revision == null then "unknown" else config.nixpkgs.revision}
    user=${cfg.user}
    desktop=${if cfg.desktop.enable then "true" else "false"}
  '';
in
{
  imports = [ ../modules/astra/ssh.nix ../modules/astra/secrets.nix ];

  # ---------------------------------------------------------------- options --
  options.astra = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install the astra baseline (account, locale, nix settings, toolchain).";
    };

    version = lib.mkOption {
      type = lib.types.str;
      default = "0.2";
      internal = true;
      description = "Version of the astra layout, stamped into /etc/astra/profile.";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "user";
      description = ''
        Name of the unprivileged account. Every host uses this one option;
        `users.users.<name>`, the home-manager entry and the groups are all
        derived from it, so renaming the account is a one-line change.
      '';
    };

    initialPassword = lib.mkOption {
      type = lib.types.str;
      default = "nixos";
      description = ''
        Password for `astra.user` at first boot. Set to "" to skip setting one
        (useful if you install over an existing account). Change it with
        `passwd` after the first login — this only ever applies to a fresh
        account.
      '';
    };

    userGroups = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "wheel" "networkmanager" ];
      description = ''
        Supplementary groups for `astra.user`. Accumulates: core adds docker,
        desktop adds video/audio/input. Host-added groups (printer, bluetooth)
        go here too.
      '';
    };

    packages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = with pkgs; [ ripgrep eza ];
      description = ''
        Packages the host should have on PATH. This is the *only* way profiles
        add packages, so what ends up in the system is always a readable
        `lib.concatLists`-style accumulation instead of five modules writing to
        `environment.systemPackages` and relying on list-merge order.
      '';
    };

    dropPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = with pkgs; [ pkgs.helix ];
      description = ''
        Subtract from the accumulated `astra.packages`. Note this only removes
        what astra itself added; packages pulled in by other modules (e.g. the
        KDE session) are out of reach, disable those modules instead.
      '';
    };

    desktop = {
      # Declared as a namespace, not a bare bool, because profiles/desktop.nix
      # adds astra.desktop.vendorTools underneath it. A parent option declared
      # with a leaf type (`type = bool`) cannot have children — that is an eval
      # error, and an obscure one.
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "True on hosts running the KDE desktop. Set by profiles/desktop.nix.";
      };
    };

    profiles = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      internal = true;
      description = "Names of the profiles that contributed to this host. Informational.";
    };

    timeZone = lib.mkOption {
      type = lib.types.str;
      default = "UTC";
      description = "IANA timezone. Override per host; UTC is the safe default for servers.";
    };

    dns = {
      servers = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [
          "9.9.9.9"   # Quad9: filters malware, logs nothing, no vendor profile
          "1.1.1.1"   # Cloudflare: fast, secondary
        ];
        description = ''
          Upstream resolvers. Quad9 first because it is the only one of the
          big three that does not build a profile of you. Override with
          `mkForce [ ]` on hosts that run their own resolver.
        '';
      };
    };

    nixGcDays = lib.mkOption {
      type = lib.types.int;
      default = 45;
      description = "Delete store paths unused for this many days (0 disables automatic GC).";
    };

    ssh = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Run sshd. Turn off for machines that never accept a remote login.";
      };

      port = lib.mkOption {
        type = lib.types.port;
        default = 22;
        description = "sshd port.";
      };

      hostKeys = lib.mkOption {
        type = lib.types.listOf lib.types.path;
        default = [ ];
        description = "Extra host keys to generate (paths). Empty means the NixOS default set.";
      };

      extraSettings = lib.mkOption {
        type = lib.types.attrs;
        default = { };
        example = { PasswordAuthentication = false; };
        description = "Merged last into `services.openssh.settings`; hosts add keys and policy here.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    astra.profiles = [ "base" ];

    # --------------------------------------------------------------- account --
    users.users.${cfg.user} = {
      isNormalUser = true;
      description = "astra";
      extraGroups = cfg.userGroups;
      # shell comes from /etc/shells via zsh below; keep it explicit so the
      # account is usable even before home-manager has run.
      shell = pkgs.zsh;
    } // lib.optionalAttrs (cfg.initialPassword != "") {
      initialPassword = cfg.initialPassword;
    };

    # ---------------------------------------------------------------- locale --
    i18n.defaultLocale = "en_US.UTF-8";
    i18n.supportedLocales = [ "en_US.UTF-8/UTF-8" ];
    # Without this glibc 2.40+ prints a warning on every start-up for the
    # default locale.
    i18n.extraLocaleSettings.LC_COLLATE = "C";
    environment.variables = {
      LANG = "en_US.UTF-8";
      EDITOR = "hx";
      PAGER = "less";
    };
    time.timeZone = cfg.timeZone;

    # ------------------------------------------------------------------ net --
    networking.networkmanager.enable = true;
    networking.nameservers = cfg.dns.servers;
    networking.firewall.enable = true;

    # ------------------------------------------------------------------ nix --
    nix.settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
      trusted-users = [ "root" "@wheel" ];
      warn-dirty = false;
    };
    nix.gc = {
      automatic = cfg.nixGcDays > 0;
      options = lib.optionalString (cfg.nixGcDays > 0) "--delete-older-than ${toString cfg.nixGcDays}d";
    };
    # Lets unpatched binaries (vendor Electron apps mostly) find their
    # libraries. One extra service, saves a class of "why won't this launch".
    services.nix-ld.enable = true;
    services.fstrim.enable = true;

    # -------------------------------------------------------------- logging --
    services.journald = {
      # services.journald declares exactly seven options in nixpkgs (console,
      # rateLimitInterval, storage, rateLimitBurst, audit, extraConfig,
      # forwardToSyslog); arbitrary journald.conf keys go in extraConfig.
      # 14 days is long enough to debug last week's boot failure and short
      # enough not to fill a laptop SSD.
      extraConfig = ''
        MaxRetentionSec=14day
        SystemMaxUse=2G
      '';
    };
    services.logind.settings.Login = {
      # These are logind.conf keys, so they belong under settings.Login — a
      # freeform submodule whose own nixpkgs example is
      # { KillUserProcesses = false; HandleLidSwitch = "ignore"; }.
      # services.logind itself only declares `enable` and `settings.Login`, and
      # services.logind.extraConfig was removed outright.
      #
      # Suspend far enough out to close the lid without draining the battery.
      IdleAction = "ignore";
      HandlePowerKey = "suspend";
      HandleLidSwitch = "suspend";
      HandleLidSwitchExternalPower = "ignore";
    };

    # --------------------------------------------------------------- paths ---
    systemd.tmpfiles.rules = [ "d /var/lib/astra 0755 root root -" ];

    environment.etc."astra/profile" = {
      text = profileFacts;
      mode = "0444";
    };

    # ---------------------------------------------------------------- pkgs ---
    environment.systemPackages = lib.subtractLists cfg.dropPackages cfg.packages
      ++ [ (import ../lib/astra-info.nix { inherit pkgs; }).package ];

    # ------------------------------------------------------- baseline pkgs ---
    # The floor every astra machine gets. Anything more specific belongs in a
    # profile above, or on the host.
    astra.packages = with pkgs; [
      alejandra # `nix fmt` formatter, also used by this repo
      curl
      eza
      git
      helix
      htop
      less # PAGER=less above
      ripgrep
      tty-clock
      wget
    ];
  };
}