name: flake check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true
      - run: nix build .#nixosConfigurations.vm-nano.config.system.build.toplevel --no-link --dry-run
      - run: nix build .#nixosConfigurations.vm-mini.config.system.build.toplevel --no-link --dry-run
      - run: nix build .#nixosConfigurations.vm-full.config.system.build.toplevel --no-link --dry-run
      - run: nix build .#nixosConfigurations.server.config.system.build.toplevel --no-link --dry-run
      - run: nix build .#nixosConfigurations.server-core.config.system.build.toplevel --no-link --dry-run
